version: "3.1"
services: 
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports: 
      - "3306:3306"
    environment: 
      "MYSQL_DATABASE": "nodejsdesafio"
      "MYSQL_ROOT_PASSWORD": "rootpassword"
    networks: 
     - desafio-node 
  webserver:
    image : nginx:mainline-alpine
    container_name: webserver
    restart: always
    ports: 
      - "8080:8080"
    networks: 
     - desafio-node
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: always
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 60s node index.js
    depends_on: 
      - mysql
    ports:
      - "3000:3000"
    networks: 
     - desafio-node
networks: 
  desafio-node:
    driver: bridge
    